# Homography
Firstly, write a function that computes homography given 4 chosen points:

In [1]:
import numpy as np
import scipy.linalg as linalg
import cv2
from PIL import Image
from pylab import *
import matplotlib as mpl
import matplotlib.pyplot as plt
import yaml
import cv2

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [3]:
def getHomography(x1, x2, x3, x4, y1, y2, y3, y4):
    print(x1, x2, x3, x4, y1, y2, y3, y4)
    A = np.array([[x1[0],x1[1],1, 0,0,0, -x1[0]*y1[0],-x1[1]*y1[0],-y1[0]],
                  [0,0,0, x1[0],x1[1],1, -x1[0]*y1[1],-x1[1]*y1[1],-y1[1]],
                  [x2[0],x2[1],1, 0,0,0, -x2[0]*y2[0],-x2[1]*y2[0],-y2[0]],
                  [0,0,0, x2[0],x2[1],1, -x2[0]*y2[1],-x2[1]*y2[1],-y2[1]],
                  [x3[0],x3[1],1, 0,0,0, -x3[0]*y3[0],-x3[1]*y3[0],-y3[0]],
                  [0,0,0, x3[0],x3[1],1, -x3[0]*y3[1],-x3[1]*y3[1],-y3[1]],
                  [x4[0],x4[1],1, 0,0,0, -x4[0]*y4[0],-x4[1]*y4[0],-y4[0]],
                  [0,0,0, x4[0],x4[1],1, -x4[0]*y4[1],-x4[1]*y4[1],-y4[1]]])
#     print(A)
    U, D, Vt = linalg.svd(A)
    H = Vt[-1].reshape(3,3)
#     print(H)
    
    return H

In [5]:
# Testing block:
# getHomography(np.array([11, 12]), np.array([21, 22]), np.array([31,32]), np.array([41,42]), 
#               np.array([110, 120]), np.array([210, 220]), np.array([310,320]), np.array([410, 420]))
# x_1 = [93,-7]
# y_1 = [63,0]
# x_2 = [293,3]
# y_2 = [868,-6]
# x_3 = [1207,7]
# y_3 = [998,-4]
# x_4 = [1218,3]
# y_4 = [309,2]

x_1 = [93,63]
y_1 = [-7,0]
x_2 = [293,868]
y_2 = [3,-6]
x_3 = [1207,998]
y_3 = [7,-4]
x_4 = [1218,309]
y_4 = [3,2]
H = getHomography(x_1, x_2, x_3, x_4, y_1, y_2, y_3, y_4)
print(H)
y_t = np.matmul(H, np.array([93,63,1]))
y_t = y_t/y_t[2]
print(y_t)
y_t = np.matmul(H, np.array([293,868,1]))
y_t = y_t/y_t[2]
print(y_t)
y_t = np.matmul(H, np.array([1207,998,1]))
y_t = y_t/y_t[2]
print(y_t)
y_t = np.matmul(H, np.array([1218,309,1]))
y_t = y_t/y_t[2]
print(y_t)

[93, 63] [293, 868] [1207, 998] [1218, 309] [-7, 0] [3, -6] [7, -4] [3, 2]
[[ 7.66575414e-04  1.58444870e-03 -9.92728904e-01]
 [ 6.18613947e-04 -1.66221257e-03  4.71882946e-02]
 [ 1.53502369e-07  1.05575751e-04  1.10708327e-01]]
[-7.00000000e+00 -8.87063696e-13  1.00000000e+00]
[ 3. -6.  1.]
[ 7. -4.  1.]
[3. 2. 1.]


In [6]:
# Testing block:
x_1 = [93,-7]
y_1 = [63,0]
x_2 = [293,3]
y_2 = [868,-6]
x_3 = [1207,7]
y_3 = [998,-4]
x_4 = [1218,3]
y_4 = [309,2]
P = np.array([
    [-x_1[0], -y_1[0], -1, 0, 0, 0, x_1[0]*x_1[1], y_1[0]*x_1[1], x_1[1]],
    [0, 0, 0, -x_1[0], -y_1[0], -1, x_1[0]*y_1[1], y_1[0]*y_1[1], y_1[1]],
    [-x_2[0], -y_2[0], -1, 0, 0, 0, x_2[0]*x_2[1], y_2[0]*x_2[1], x_2[1]],
    [0, 0, 0, -x_2[0], -y_2[0], -1, x_2[0]*y_2[1], y_2[0]*y_2[1], y_2[1]],
    [-x_3[0], -y_3[0], -1, 0, 0, 0, x_3[0]*x_3[1], y_3[0]*x_3[1], x_3[1]],
    [0, 0, 0, -x_3[0], -y_3[0], -1, x_3[0]*y_3[1], y_3[0]*y_3[1], y_3[1]],
    [-x_4[0], -y_4[0], -1, 0, 0, 0, x_4[0]*x_4[1], y_4[0]*x_4[1], x_4[1]],
    [0, 0, 0, -x_4[0], -y_4[0], -1, x_4[0]*y_4[1], y_4[0]*y_4[1], y_4[1]],
    ])

[U, S, Vt] = np.linalg.svd(P)
homography = Vt[-1].reshape(3, 3)
print(homography)
# transformedPoint = homography @ np.array([1679,  128, 1]).transpose()
# print(transformedPoint/transformedPoint[-1]) # will be ~[4, 7, 1]

[[ 7.66575414e-04  1.58444870e-03 -9.92728904e-01]
 [ 6.18613947e-04 -1.66221257e-03  4.71882946e-02]
 [ 1.53502369e-07  1.05575751e-04  1.10708327e-01]]


Second of all, allow users to select points on images:

In [4]:
%matplotlib tk
def choosePoints(img1, img2):

    matplotlib.use('TkAgg')

#     img1 = Image.open('h1.jpg')
#     arrImg1 = np.array(img1)
    imshow(img1, interpolation='none')
    chosenPoints1 = ginput(4) 
    print(chosenPoints1)
    
#     img2 = Image.open('h2.jpg')
#     arrImg2 = np.array(img2)
    imshow(img2, interpolation='none')
    chosenPoints2 = ginput(4) 
    print(chosenPoints2)
    
    return chosenPoints1, chosenPoints2

Third of all, we need to involve our images with the getHomography function. So we need to import the images, then compute image matrix multiplying with the homography.

In [110]:
def computeHomographyTransformation(img1, img2):
#     img1 = cv2.imread('h1.jpg')
#     arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
#     img2 = cv2.imread('h2.jpg')
#     arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
    imgSizeX = img1.shape[0]
    imgSizeY = img1.shape[1]
    newSizeX = img2.shape[0] 
    newSizeY = img2.shape[1]
    newImg = np.zeros((newSizeX, newSizeY, 3),np.uint8)
    
#     # read the chosen points:
#     chosenPts1, chosenPts2 = choosePoints(img1, img2)
#     H = getHomography(chosenPts1[0], chosenPts1[1], chosenPts1[2], chosenPts1[3],
#                       chosenPts2[0], chosenPts2[1], chosenPts2[2], chosenPts2[3])
#     HInverse = np.linalg.pinv(H)
    
#     newImg = cv2.warpPerspective(img1, H, (newSizeY,newSizeX))
    
    # read the chosen points:
    chosenPts1, chosenPts2 = choosePoints(img1, img2)
    
    H = getHomography(chosenPts1[0], chosenPts1[1], chosenPts1[2], chosenPts1[3],
                      chosenPts2[0], chosenPts2[1], chosenPts2[2], chosenPts2[3])
    HInverse = np.linalg.pinv(H)
    
    for i in range(0, newSizeY):
        for j in range(0, newSizeX):
            newPos = np.array([i, j, 1])
            orgPos = HInverse.dot(newPos) # find the corresponding indexes in the original image by H^(-1)
            orgPos = orgPos/orgPos[2] # normalize the indexes
            orgPosX = int(orgPos[0]) # round the indexes to integer
            orgPosY = int(orgPos[1])
            if((orgPosX >= 0 and orgPosX < imgSizeY) and (orgPosY >= 0 and orgPosY < imgSizeX)):
                newImg[j][i] = img1[orgPosY][orgPosX]    
    
    
    
#     # transform img1 to img2:
#     for i in range(0, newSizeX):
#         for j in range(0,newSizeY):
#             newPos = np.array([i, j, 1])
# #             if(i==293):
# #                 print('newPos:')
# #                 print(newPos)
#             orgPos = np.matmul(HInverse, newPos) # find the corresponding indexes in the original image by H^(-1)
#             orgPos = orgPos/orgPos[2] # normalize the indexes
#             orgPosX = int(orgPos[0]) # round the indexes to integer
#             orgPosY = int(orgPos[1])
#             if(orgPosX >= 0 and orgPosX < imgSizeX and orgPosY >= 0 and orgPosY < imgSizeY):
#                 newImg[i][j] = img1[orgPosX][orgPosY]
# #             newPos = np.matmul(H, np.array([i,j,1]))
# #             newPos = newPos/newPos[2]
# #             newPosX = int(newPos[0])
# #             newPosY = int(newPos[1])
# #             if(newPosX >=0 and newPosX < imgSizeX and newPosY >=0 and newPosY < imgSizeY):
# #                 newImg[newPosX][newPosY] = img1[i][j]
    # Draw img
#     plt.imshow(cv2.cvtColor(newImg,cv2.COLOR_BGR2RGB), interpolation='none')
    plt.imshow(newImg/255)
    plt.show()

In [112]:
# Testing block
img1 = cv2.imread('h1.jpg')
img2 = cv2.imread('h2.jpg')
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
computeHomographyTransformation(img1, img2)

[(67.49116997792487, 73.67218543046374), (1149.1688741721855, 57.11589403973517), (45.41611479028688, 1133.2748344370862), (1116.0562913907283, 1144.3123620309052)]
[(53.575607064017674, 205.8570640176601), (477.4120676968361, 14.185798381162726), (353.2306843267109, 519.0101177336277), (806.7626931567331, 276.0465415746873)]
[(95.08498896247227, 57.11589403973517), (1160.206401766004, 57.11589403973517), (67.49116997792487, 1160.8686534216336), (1160.206401766004, 1138.7935982339957)]
[(53.575607064017674, 213.95584988962474), (450.41611479028717, 27.683774834437145), (385.6258278145696, 500.11295069904344), (795.9643119941136, 292.24411331861666)]
(95.08498896247227, 57.11589403973517) (1160.206401766004, 57.11589403973517) (67.49116997792487, 1160.8686534216336) (1160.206401766004, 1138.7935982339957) (53.575607064017674, 213.95584988962474) (450.41611479028717, 27.683774834437145) (385.6258278145696, 500.11295069904344) (795.9643119941136, 292.24411331861666)


In [113]:
# Testing block
img1 = cv2.imread('h1.jpg')
img2 = cv2.imread('h2.jpg')
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
computeHomographyTransformation(img2, img1)

[(53.575607064017674, 205.8570640176601), (469.31328182487135, 19.584988962472494), (377.52704194260497, 524.4093083149374), (798.6639072847686, 286.8449227373069)]
[(56.45364238410582, 79.19094922737327), (1154.6876379690948, 57.11589403973517), (73.0099337748344, 1122.237306843267), (1138.1313465783664, 1122.237306843267)]
[(40.0776306107432, 203.1574687270052), (463.9140912435616, 27.683774834437145), (369.4282560706403, 524.4093083149374), (804.0630978660784, 289.5445180279618)]
[(67.49116997792487, 46.07836644591612), (1187.800220750552, 51.59713024282564), (56.45364238410582, 1138.7935982339957), (1132.6125827814567, 1127.7560706401766)]
(40.0776306107432, 203.1574687270052) (463.9140912435616, 27.683774834437145) (369.4282560706403, 524.4093083149374) (804.0630978660784, 289.5445180279618) (67.49116997792487, 46.07836644591612) (1187.800220750552, 51.59713024282564) (56.45364238410582, 1138.7935982339957) (1132.6125827814567, 1127.7560706401766)


Now, for the Simpsons case:

In [23]:
def getMinMax(array):
    minX = np.min(array[0,:])
    minY = np.min(array[1,:])
    maxX = np.max(array[0,:])
    maxY = np.max(array[1,:])
    return minX, minY, maxX, maxY

In [26]:
# Testing block:
array = np.array([[3,1,1,11,-11,3,-7],[-1,0,1,19,21,-100,0],[1,1,1,1,1,1,1]])
print(getMinMax(array))

(-11, -100, 11, 21)


In [108]:
def computeHomographyAndConcat(img1, img2):
#     img1 = cv2.imread('h1.jpg')
#     arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
#     img2 = cv2.imread('h2.jpg')
#     arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
    imgSizeX = img1.shape[0]
    imgSizeY = img1.shape[1]
    newSizeX = img2.shape[0] 
    newSizeY = img2.shape[1]
    newImg = img2
    
    # read the chosen points:
    chosenPts1, chosenPts2 = choosePoints(img1, img2)
    
    H = getHomography(chosenPts1[0], chosenPts1[1], chosenPts1[2], chosenPts1[3],
                      chosenPts2[0], chosenPts2[1], chosenPts2[2], chosenPts2[3])
    HInverse = np.linalg.pinv(H)

    
    for i in range(0, newSizeY):
        for j in range(0, newSizeX):
            newPos = np.array([i, j, 1])
            orgPos = HInverse.dot(newPos) # find the corresponding indexes in the original image by H^(-1)
            orgPos = orgPos/orgPos[2] # normalize the indexes
            orgPosX = int(orgPos[0]) # round the indexes to integer
            orgPosY = int(orgPos[1])
            if((orgPosX >= 0 and orgPosX < imgSizeY) and (orgPosY >= 0 and orgPosY < imgSizeX)):
                newImg[j][i] = img1[orgPosY][orgPosX]       
                
    # Draw img
    plt.imshow(newImg/255)
    plt.show()

In [109]:
# Testing block
imgSimpsons = cv2.imread('simpsons.jpg')
imgSimpsons = cv2.cvtColor(imgSimpsons, cv2.COLOR_BGR2RGB)
imgBus = cv2.imread('bus.jpg')
imgBus = cv2.cvtColor(imgBus, cv2.COLOR_BGR2RGB)
computeHomographyAndConcat(imgSimpsons, imgBus)

[(13.459062325146306, 19.142066759643512), (978.0248407004999, 16.63670110152566), (13.459062325146306, 1482.27561110044), (985.5409376748532, 1477.2648797842044)]
[(581.5316845243561, 208.26537250611716), (795.2928229625111, 231.08257267648207), (597.1434530619742, 518.0989327142296), (803.6991598673824, 465.259100740753)]
(13.459062325146306, 19.142066759643512) (978.0248407004999, 16.63670110152566) (13.459062325146306, 1482.27561110044) (985.5409376748532, 1477.2648797842044) (581.5316845243561, 208.26537250611716) (795.2928229625111, 231.08257267648207) (597.1434530619742, 518.0989327142296) (803.6991598673824, 465.259100740753)


In [84]:
# # Testing block
# # img1 = Image.open('h1.jpg'), cv2.COLOR_BGR2RGB
# # img2 = Image.open('h2.jpg'), cv2.COLOR_BGR2RGB
# # arrImg1 = np.array(img1.convert('L'),'f')
# # arrImg2 = np.array(img2.convert('L'),'f')
# arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
# arrImg2 = np.array(Image.open('h2.jpg').convert('L'),'f')
# # arrImg1 = cv2.cvtColor(arrImg1, cv2.COLOR_BGR2RGB) # Working
# # arrImg2 = cv2.cvtColor(arrImg2, cv2.COLOR_BGR2RGB) # Not Working

# # arrImg1 = np.array(img1.convert('L'),'f')
# # arrImg2 = np.array(img2.convert('L'),'f')
# computeHomographyTransformation(arrImg1, arrImg2)
# # arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
# # arrImg2 = np.array(Image.open('h2.jpg').convert('L'),'f')
# # computeHomographyTransformation(img1, img2)

In [85]:
# arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
# arrImg2 = np.array(Image.open('h2.jpg').convert('L'),'f')
# computeHomographyTransformation(arrImg2, arrImg1)

In [86]:
# import matplotlib
# %matplotlib tk

# matplotlib.use('TkAgg')

# img1 = Image.open('h1.jpg')
# arrImg1 = np.array(img1)
# imshow(img1)

# chosenPoints1 = ginput(4) 
# print(chosenPoints1)


In [87]:
# img2 = Image.open('h2.jpg')
# arrImg2 = np.array(img2)
# imshow(img2)

# chosenPoints2 = ginput(4) 
# print(chosenPoints2)