# Homography
Firstly, write a function that computes homography given 4 chosen points:

In [38]:
import numpy as np
import scipy.linalg as linalg
import cv2
from PIL import Image
from pylab import *
import matplotlib as mpl
import matplotlib.pyplot as plt
import yaml
import cv2

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [39]:
def getHomography(x1, x2, x3, x4, y1, y2, y3, y4):
    print(x1, x2, x3, x4, y1, y2, y3, y4)
    A = np.array([[x1[0],x1[1],1, 0,0,0, -x1[0]*y1[0],-x1[1]*y1[0],-y1[0]],
                  [0,0,0, x1[0],x1[1],1, -x1[0]*y1[1],-x1[1]*y1[1],-y1[1]],
                  [x2[0],x2[1],1, 0,0,0, -x2[0]*y2[0],-x2[1]*y2[0],-y2[0]],
                  [0,0,0, x2[0],x2[1],1, -x2[0]*y2[1],-x2[1]*y2[1],-y2[1]],
                  [x3[0],x3[1],1, 0,0,0, -x3[0]*y3[0],-x3[1]*y3[0],-y3[0]],
                  [0,0,0, x3[0],x3[1],1, -x3[0]*y3[1],-x3[1]*y3[1],-y3[1]],
                  [x4[0],x4[1],1, 0,0,0, -x4[0]*y4[0],-x4[1]*y4[0],-y4[0]],
                  [0,0,0, x4[0],x4[1],1, -x4[0]*y4[1],-x4[1]*y4[1],-y4[1]]])
#     print(A)
    U, D, Vt = linalg.svd(A)
    H = Vt[-1].reshape(3,3)
#     print(H)
    
    return H

In [57]:
# Testing block:
# getHomography(np.array([11, 12]), np.array([21, 22]), np.array([31,32]), np.array([41,42]), 
#               np.array([110, 120]), np.array([210, 220]), np.array([310,320]), np.array([410, 420]))
# x_1 = [93,-7]
# y_1 = [63,0]
# x_2 = [293,3]
# y_2 = [868,-6]
# x_3 = [1207,7]
# y_3 = [998,-4]
# x_4 = [1218,3]
# y_4 = [309,2]

x_1 = [93,63]
y_1 = [-7,0]
x_2 = [293,868]
y_2 = [3,-6]
x_3 = [1207,998]
y_3 = [7,-4]
x_4 = [1218,309]
y_4 = [3,2]
H = getHomography(x_1, x_2, x_3, x_4, y_1, y_2, y_3, y_4)
print(H)
y_t = np.matmul(H, np.array([293,868,1]))
y_t = y_t/y_t[2]
print(y_t)

[93, 63] [293, 868] [1207, 998] [1218, 309] [-7, 0] [3, -6] [7, -4] [3, 2]
[[ 7.66575414e-04  1.58444870e-03 -9.92728904e-01]
 [ 6.18613947e-04 -1.66221257e-03  4.71882946e-02]
 [ 1.53502369e-07  1.05575751e-04  1.10708327e-01]]
[ 3. -6.  1.]


In [41]:
# Testing block:
x_1 = [93,-7]
y_1 = [63,0]
x_2 = [293,3]
y_2 = [868,-6]
x_3 = [1207,7]
y_3 = [998,-4]
x_4 = [1218,3]
y_4 = [309,2]
P = np.array([
    [-x_1[0], -y_1[0], -1, 0, 0, 0, x_1[0]*x_1[1], y_1[0]*x_1[1], x_1[1]],
    [0, 0, 0, -x_1[0], -y_1[0], -1, x_1[0]*y_1[1], y_1[0]*y_1[1], y_1[1]],
    [-x_2[0], -y_2[0], -1, 0, 0, 0, x_2[0]*x_2[1], y_2[0]*x_2[1], x_2[1]],
    [0, 0, 0, -x_2[0], -y_2[0], -1, x_2[0]*y_2[1], y_2[0]*y_2[1], y_2[1]],
    [-x_3[0], -y_3[0], -1, 0, 0, 0, x_3[0]*x_3[1], y_3[0]*x_3[1], x_3[1]],
    [0, 0, 0, -x_3[0], -y_3[0], -1, x_3[0]*y_3[1], y_3[0]*y_3[1], y_3[1]],
    [-x_4[0], -y_4[0], -1, 0, 0, 0, x_4[0]*x_4[1], y_4[0]*x_4[1], x_4[1]],
    [0, 0, 0, -x_4[0], -y_4[0], -1, x_4[0]*y_4[1], y_4[0]*y_4[1], y_4[1]],
    ])

[U, S, Vt] = np.linalg.svd(P)
homography = Vt[-1].reshape(3, 3)
print(homography)
# transformedPoint = homography @ np.array([1679,  128, 1]).transpose()
# print(transformedPoint/transformedPoint[-1]) # will be ~[4, 7, 1]

[[ 7.66575414e-04  1.58444870e-03 -9.92728904e-01]
 [ 6.18613947e-04 -1.66221257e-03  4.71882946e-02]
 [ 1.53502369e-07  1.05575751e-04  1.10708327e-01]]


Second of all, allow users to select points on images:

In [42]:
%matplotlib tk
def choosePoints(img1, img2):

    matplotlib.use('TkAgg')

#     img1 = Image.open('h1.jpg')
#     arrImg1 = np.array(img1)
    imshow(img1, interpolation='none')
    chosenPoints1 = ginput(4) 
    print(chosenPoints1)
    
#     img2 = Image.open('h2.jpg')
#     arrImg2 = np.array(img2)
    imshow(img2, interpolation='none')
    chosenPoints2 = ginput(4) 
    print(chosenPoints2)
    
    return chosenPoints1, chosenPoints2

Third of all, we need to involve our images with the getHomography function. So we need to import the images, then compute image matrix multiplying with the homography.

In [ ]:
def computeHomographyTransformation(img1, img2):
#     img1 = cv2.imread('h1.jpg')
#     arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
#     img2 = cv2.imread('h2.jpg')
#     arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
    imgSizeX = img1.shape[0]
    imgSizeY = img1.shape[1]
    newSizeX = img2.shape[0]*2
    newSizeY = img2.shape[1]*2
    newImg = np.zeros((newSizeX, newSizeY, 3),np.uint8)
    
    # read the chosen points:
    chosenPts1, chosenPts2 = choosePoints(img1, img2)
    
    
    H = getHomography(chosenPts1[0], chosenPts1[1], chosenPts1[2], chosenPts1[3],
                      chosenPts2[0], chosenPts2[1], chosenPts2[2], chosenPts2[3])
    HInverse = np.linalg.pinv(H)
#     H = getHomography(chosenPts1[0], chosenPts1[1], chosenPts1[2], chosenPts1[3],
#                       chosenPts1[0], chosenPts1[1], chosenPts1[2], chosenPts1[3])
    
    # transform img1 to img2:
    for i in range(0, newSizeX):
        for j in range(0,newSizeY):
            newPos = np.array([i, j, 1])
#             print(newPos)
            orgPos = np.matmul(HInverse, newPos)
            orgPos = orgPos/orgPos[2]
#             print(orgPos)
            orgPosX = orgPos[0]
            orgPosY = orgPos[1]
            if(orgPosX >= 0 and orgPosX < imgSizeX and orgPosY >= 0 and orgPosY < imgSizeY):
                newImg[i][j] = img1[int(orgPos[0])][int(orgPos[1])]
#             newPos = np.matmul(H, np.array([i,j,1]))
#             newPos = newPos/newPos[2]
#             newPosX = int(newPos[0])
#             newPosY = int(newPos[1])
#             if(newPosX >=0 and newPosX < imgSizeX and newPosY >=0 and newPosY < imgSizeY):
#                 newImg[newPosX][newPosY] = img1[i][j]
    # Draw img
    plt.imshow(cv2.cvtColor(newImg,cv2.COLOR_BGR2RGB), interpolation='none')
    plt.show()

In [46]:
# Testing block
img1 = Image.open('h1.jpg')
img2 = Image.open('h2.jpg')
arrImg1 = np.array(img1.convert('L'),'f')
arrImg2 = np.array(img2.convert('L'),'f')
computeHomographyTransformation(arrImg1, arrImg2)
# arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
# arrImg2 = np.array(Image.open('h2.jpg').convert('L'),'f')
# computeHomographyTransformation(img1, img2)

[(194.42273730684315, 195.0849889624726), (1011.1997792494479, 195.0849889624726), (183.3852097130242, 1022.8995584988963), (1011.1997792494479, 1022.8995584988963)]
[(218.2509197939662, 76.27649006622528), (704.1780721118471, 89.7744665194997), (696.0792862398825, 273.3469462840324), (191.25496688741725, 438.0222590139809)]
(194.42273730684315, 195.0849889624726) (1011.1997792494479, 195.0849889624726) (183.3852097130242, 1022.8995584988963) (1011.1997792494479, 1022.8995584988963) (218.2509197939662, 76.27649006622528) (704.1780721118471, 89.7744665194997) (696.0792862398825, 273.3469462840324) (191.25496688741725, 438.0222590139809)


In [59]:
arrImg1 = np.array(Image.open('h1.jpg').convert('L'),'f')
arrImg2 = np.array(Image.open('h2.jpg').convert('L'),'f')
computeHomographyTransformation(arrImg2, arrImg1)

[(326.234731420162, 273.3469462840324), (488.21044885945565, 181.56070640176603), (399.12380426784415, 348.93561442236944), (571.8979028697574, 257.14937454010305)]
[(542.1048565121413, 498.61699779249454), (680.0739514348785, 515.173289183223), (553.1423841059601, 653.1423841059603), (680.0739514348785, 642.1048565121414)]
(326.234731420162, 273.3469462840324) (488.21044885945565, 181.56070640176603) (399.12380426784415, 348.93561442236944) (571.8979028697574, 257.14937454010305) (542.1048565121413, 498.61699779249454) (680.0739514348785, 515.173289183223) (553.1423841059601, 653.1423841059603) (680.0739514348785, 642.1048565121414)


In [13]:
# import matplotlib
# %matplotlib tk

# matplotlib.use('TkAgg')

# img1 = Image.open('h1.jpg')
# arrImg1 = np.array(img1)
# imshow(img1)

# chosenPoints1 = ginput(4) 
# print(chosenPoints1)


[(195.3195364238411, 219.91942604856513), (990.0215231788081, 219.91942604856513), (209.1164459161148, 962.1931567328919), (1006.5778145695367, 959.4337748344371)]


In [14]:
# img2 = Image.open('h2.jpg')
# arrImg2 = np.array(img2)
# imshow(img2)

# chosenPoints2 = ginput(4) 
# print(chosenPoints2)

[(454.9041919610008, 84.37527593818993), (193.0434487674761, 227.45382634289922), (693.8183751839588, 289.5445180279618), (394.1632979212656, 448.8206401766005)]
